
<!DOCTYPE html>
<html lang="en">

<!--================================================================================
	Item Name: Materialize - Material Design Admin Template
	Version: 3.1
	Author: GeeksLabs
	Author URL: http://www.themeforest.net/user/geekslabs
================================================================================ -->

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="msapplication-tap-highlight" content="no">
	<meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
	<meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
	<title>Materialize - Material Design Admin Template</title>

	<!-- Favicons-->
	<link rel="icon" href="images/favicon/favicon-32x32.png" sizes="32x32">
	<!-- Favicons-->
	<link rel="apple-touch-icon-precomposed" href="images/favicon/apple-touch-icon-152x152.png">
	<!-- For iPhone -->
	<meta name="msapplication-TileColor" content="#00bcd4">
	<meta name="msapplication-TileImage" content="images/favicon/mstile-144x144.png">
	<!-- For Windows Phone -->

	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

	<!-- CORE CSS-->
	<link href="node_modules/materialize-css/dist/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection">
	<link href="css/style.min.css" type="text/css" rel="stylesheet" media="screen,projection">
	<!-- Custome CSS-->
	<link href="css/custom.css" type="text/css" rel="stylesheet" media="screen,projection">


	<!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
	<link href="js/plugins/perfect-scrollbar.css" type="text/css" rel="stylesheet" media="screen,projection">
	<link href="js/plugins/jquery-jvectormap.css" type="text/css" rel="stylesheet" media="screen,projection">
	<link href="js/plugins/chartist.min.css" type="text/css" rel="stylesheet" media="screen,projection">


</head>

<body class="loaded">
<!-- Start Page Loading -->
<div id="loader-wrapper">
	<div id="loader"></div>
	<div class="loader-section section-left"></div>
	<div class="loader-section section-right"></div>
</div>
<!-- End Page Loading -->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START HEADER -->
<header id="header" class="page-topbar">
	<!-- start header nav-->
	<div class="navbar-fixed">
		<nav class="navbar-color">
			<div class="nav-wrapper">
				<ul class="left">
					<li><h1 class="logo-wrapper"><a href="index.html" class="brand-logo darken-1"><img src="images/materialize-logo.png" alt="materialize logo"></a> <span class="logo-text">Materialize</span></h1></li>
				</ul>
				<div class="header-search-wrapper hide-on-med-and-down">
					<i class="mdi-action-search"></i>
					<input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explore Materialize"/>
				</div>
				<ul class="right hide-on-med-and-down">
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light translation-button"  data-activates="translation-dropdown"><img src="images/United-States.png" alt="USA" /></a>
					</li>
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
					</li>
					<li><a href="javascript:void(0);" class="waves-effect waves-block waves-light notification-button" data-activates="notifications-dropdown"><i class="mdi-social-notifications"><small class="notification-badge">5</small></i>

						</a>
					</li>
					<li><a href="#" data-activates="chat-out" class="waves-effect waves-block waves-light chat-collapse"><i class="mdi-communication-chat"></i></a>
					</li>
				</ul>
				<!-- translation-button -->
				<ul id="translation-dropdown" class="dropdown-content">
					<li>
						<a href="#!"><img src="images/United-States.png" alt="English" />  <span class="language-select">English</span></a>
					</li>
					<li>
						<a href="#!"><img src="images/France.png" alt="French" />  <span class="language-select">French</span></a>
					</li>
					<li>
						<a href="#!"><img src="images/China.png" alt="Chinese" />  <span class="language-select">Chinese</span></a>
					</li>
					<li>
						<a href="#!"><img src="images/Germany.png" alt="German" />  <span class="language-select">German</span></a>
					</li>

				</ul>
				<!-- notifications-dropdown -->
				<ul id="notifications-dropdown" class="dropdown-content">
					<li>
						<h5>NOTIFICATIONS <span class="new badge">5</span></h5>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#!"><i class="mdi-action-add-shopping-cart"></i> A new order has been placed!</a>
						<time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
					</li>
					<li>
						<a href="#!"><i class="mdi-action-stars"></i> Completed the task</a>
						<time class="media-meta" datetime="2015-06-12T20:50:48+08:00">3 days ago</time>
					</li>
					<li>
						<a href="#!"><i class="mdi-action-settings"></i> Settings updated</a>
						<time class="media-meta" datetime="2015-06-12T20:50:48+08:00">4 days ago</time>
					</li>
					<li>
						<a href="#!"><i class="mdi-editor-insert-invitation"></i> Director meeting started</a>
						<time class="media-meta" datetime="2015-06-12T20:50:48+08:00">6 days ago</time>
					</li>
					<li>
						<a href="#!"><i class="mdi-action-trending-up"></i> Generate monthly report</a>
						<time class="media-meta" datetime="2015-06-12T20:50:48+08:00">1 week ago</time>
					</li>
				</ul>
			</div>
		</nav>
	</div>
	<!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START MAIN -->
<div id="main">
	<!-- START WRAPPER -->
	<div class="wrapper">

		<!-- START LEFT SIDEBAR NAV-->
		<aside id="left-sidebar-nav">
			<ul id="slide-out" class="side-nav fixed leftside-navigation">
				<li class="user-details cyan darken-2">
					<div class="row">
						<div class="col col s4 m4 l4">
							<img src="images/avatar.jpg" alt="" class="circle responsive-img valign profile-image">
						</div>
						<div class="col col s8 m8 l8">
							<ul id="profile-dropdown" class="dropdown-content">
								<li><a href="#"><i class="mdi-action-face-unlock"></i> Profile</a>
								</li>
								<li><a href="#"><i class="mdi-action-settings"></i> Settings</a>
								</li>
								<li><a href="#"><i class="mdi-communication-live-help"></i> Help</a>
								</li>
								<li class="divider"></li>
								<li><a href="#"><i class="mdi-action-lock-outline"></i> Lock</a>
								</li>
								<li><a href="#"><i class="mdi-hardware-keyboard-tab"></i> Logout</a>
								</li>
							</ul>
							<a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown">John Doe<i class="mdi-navigation-arrow-drop-down right"></i></a>
							<p class="user-roal">Administrator</p>
						</div>
					</div>
				</li>
				<li class="bold <?= $this->active->Home ?>">
					<a href="Home" class="waves-effect waves-cyan">
						<i class="material-icons">dashboard</i>
						Home</a>
				</li>
				<li class="bold <?= $this->active->CheckVideo ?>">
					<a href="CheckVideo" class="waves-effect waves-cyan">
						<i class="material-icons">videocam</i>
						Check Video</a>
				</li>
				<li class="bold <?= $this->active->AdjustCamera ?>">
					<a href="AdjustCamera" class="waves-effect waves-cyan">
						<i class="material-icons">email</i> Adjust Camera</a>
				</li>
				<li class="bold <?= $this->active->CollectImages ?>">
					<a href="CollectImages" class="waves-effect waves-cyan">
						<i class="material-icons">queue</i>
						Collect Images</a>
				</li>
				<li class="bold <?= $this->active->CheckTraining ?>">
					<a href="CheckTraining" class="waves-effect waves-cyan">
						<i class="material-icons">check</i>
						Check Training Data</a>
				</li>
				<li class="bold">
					<a href="LearnOCR" class="waves-effect waves-cyan">
						<i class="material-icons">invert_colors</i> Learn OCR</a>
				</li>
				<li class="bold">
					<a href="TestOCR" class="waves-effect waves-cyan">
						<i class="material-icons">pages</i> Test OCR</a>
				</li>
				<li class="bold">
					<a href="ManageMain"><i class="material-icons">format_color_fill</i> Manage Main</a>
				</li>
				<li class="li-hover"><div class="divider"></div></li>
				<li class="li-hover"><p class="ultra-small margin more-text">Daily Sales</p></li>
				<li class="li-hover">
					<div class="row">
						<div class="col s12 m12 l12">
							<div class="sample-chart-wrapper">
								<div class="ct-chart ct-golden-section" id="ct2-chart"></div>
							</div>
						</div>
					</div>
				</li>
			</ul>
			<a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
		</aside>
		<!-- END LEFT SIDEBAR NAV-->

		<!-- //////////////////////////////////////////////////////////////////////////// -->

		<!-- START CONTENT -->
		<section id="content">

			<!--start container-->
			<div class="container">

				<?= $this->s($this->content) ?>


			</div>
			<!--end container-->
		</section>
		<!-- END CONTENT -->

		<!-- //////////////////////////////////////////////////////////////////////////// -->
		<!-- START RIGHT SIDEBAR NAV-->
		<aside id="right-sidebar-nav">
			<ul id="chat-out" class="side-nav rightside-navigation">
				<li class="li-hover">
					<a href="#" data-activates="chat-out" class="chat-close-collapse right"><i class="mdi-navigation-close"></i></a>
					<div id="right-search" class="row">
						<form class="col s12">
							<div class="input-field">
								<i class="mdi-action-search prefix"></i>
								<input id="icon_prefix" type="text" class="validate">
								<label for="icon_prefix">Search</label>
							</div>
						</form>
					</div>
				</li>
				<li class="li-hover">
					<ul class="chat-collapsible" data-collapsible="expandable">
						<li>
							<div class="collapsible-header teal white-text active"><i class="mdi-social-whatshot"></i>Recent Activity</div>
							<div class="collapsible-body recent-activity">
								<div class="recent-activity-list chat-out-list row">
									<div class="col s3 recent-activity-list-icon"><i class="mdi-action-add-shopping-cart"></i>
									</div>
									<div class="col s9 recent-activity-list-text">
										<a href="#">just now</a>
										<p>Jim Doe Purchased new equipments for zonal office.</p>
									</div>
								</div>
								<div class="recent-activity-list chat-out-list row">
									<div class="col s3 recent-activity-list-icon"><i class="mdi-device-airplanemode-on"></i>
									</div>
									<div class="col s9 recent-activity-list-text">
										<a href="#">Yesterday</a>
										<p>Your Next flight for USA will be on 15th August 2015.</p>
									</div>
								</div>
								<div class="recent-activity-list chat-out-list row">
									<div class="col s3 recent-activity-list-icon"><i class="mdi-action-settings-voice"></i>
									</div>
									<div class="col s9 recent-activity-list-text">
										<a href="#">5 Days Ago</a>
										<p>Natalya Parker Send you a voice mail for next conference.</p>
									</div>
								</div>
								<div class="recent-activity-list chat-out-list row">
									<div class="col s3 recent-activity-list-icon"><i class="mdi-action-store"></i>
									</div>
									<div class="col s9 recent-activity-list-text">
										<a href="#">Last Week</a>
										<p>Jessy Jay open a new store at S.G Road.</p>
									</div>
								</div>
								<div class="recent-activity-list chat-out-list row">
									<div class="col s3 recent-activity-list-icon"><i class="mdi-action-settings-voice"></i>
									</div>
									<div class="col s9 recent-activity-list-text">
										<a href="#">5 Days Ago</a>
										<p>Natalya Parker Send you a voice mail for next conference.</p>
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="collapsible-header light-blue white-text active"><i class="mdi-editor-attach-money"></i>Sales Repoart</div>
							<div class="collapsible-body sales-repoart">
								<div class="sales-repoart-list  chat-out-list row">
									<div class="col s8">Target Salse</div>
									<div class="col s4"><span id="sales-line-1"></span>
									</div>
								</div>
								<div class="sales-repoart-list chat-out-list row">
									<div class="col s8">Payment Due</div>
									<div class="col s4"><span id="sales-bar-1"></span>
									</div>
								</div>
								<div class="sales-repoart-list chat-out-list row">
									<div class="col s8">Total Delivery</div>
									<div class="col s4"><span id="sales-line-2"></span>
									</div>
								</div>
								<div class="sales-repoart-list chat-out-list row">
									<div class="col s8">Total Progress</div>
									<div class="col s4"><span id="sales-bar-2"></span>
									</div>
								</div>
							</div>
						</li>
						<li>
							<div class="collapsible-header red white-text"><i class="mdi-action-stars"></i>Favorite Associates</div>
							<div class="collapsible-body favorite-associates">
								<div class="favorite-associate-list chat-out-list row">
									<div class="col s4"><img src="images/avatar.jpg" alt="" class="circle responsive-img online-user valign profile-image">
									</div>
									<div class="col s8">
										<p>Eileen Sideways</p>
										<p class="place">Los Angeles, CA</p>
									</div>
								</div>
								<div class="favorite-associate-list chat-out-list row">
									<div class="col s4"><img src="images/avatar.jpg" alt="" class="circle responsive-img online-user valign profile-image">
									</div>
									<div class="col s8">
										<p>Zaham Sindil</p>
										<p class="place">San Francisco, CA</p>
									</div>
								</div>
								<div class="favorite-associate-list chat-out-list row">
									<div class="col s4"><img src="images/avatar.jpg" alt="" class="circle responsive-img offline-user valign profile-image">
									</div>
									<div class="col s8">
										<p>Renov Leongal</p>
										<p class="place">Cebu City, Philippines</p>
									</div>
								</div>
								<div class="favorite-associate-list chat-out-list row">
									<div class="col s4"><img src="images/avatar.jpg" alt="" class="circle responsive-img online-user valign profile-image">
									</div>
									<div class="col s8">
										<p>Weno Carasbong</p>
										<p>Tokyo, Japan</p>
									</div>
								</div>
								<div class="favorite-associate-list chat-out-list row">
									<div class="col s4"><img src="images/avatar.jpg" alt="" class="circle responsive-img offline-user valign profile-image">
									</div>
									<div class="col s8">
										<p>Nusja Nawancali</p>
										<p class="place">Bangkok, Thailand</p>
									</div>
								</div>
							</div>
						</li>
					</ul>
				</li>
			</ul>
		</aside>
		<!-- LEFT RIGHT SIDEBAR NAV-->

	</div>
	<!-- END WRAPPER -->

</div>
<!-- END MAIN -->



<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START FOOTER -->
<footer class="page-footer">
<!--	<div class="container">
		<div class="row section">
			<div class="col l6 s12">
				<h5 class="white-text">World Market</h5>
				<p class="grey-text text-lighten-4">World map, world regions, countries and cities.</p>
				<div id="world-map-markers"></div>
			</div>
			<div class="col l4 offset-l2 s12">
				<h5 class="white-text">Sales by Country</h5>
				<p class="grey-text text-lighten-4">A sample polar chart to show sales by country.</p>
				<div id="polar-chart-holder">
					<canvas id="polar-chart-country" width="200"></canvas>
				</div>
			</div>
		</div>
	</div>
-->	<div class="footer-copyright">
		<div class="container">
			Copyright © 2015 <a class="grey-text text-lighten-4" href="http://themeforest.net/user/geekslabs/portfolio?ref=geekslabs" target="_blank">GeeksLabs</a> All rights reserved.
			<span class="right"> Design and Developed by <a class="grey-text text-lighten-4" href="http://geekslabs.com/">GeeksLabs</a></span>
		</div>
	</div>
</footer>
<!-- END FOOTER -->


<!-- ================================================
Scripts
================================================ -->

<!-- jQuery Library -->
<script type="text/javascript" src="js/plugins/jquery-1.11.2.min.js"></script>
<!--materialize js-->
<script type="text/javascript" src="node_modules/materialize-css/dist/js/materialize.min.js"></script>
<!--scrollbar-->
<script type="text/javascript" src="js/plugins/perfect-scrollbar.min.js"></script>


<!-- chartist -->
<script type="text/javascript" src="js/plugins/chartist.min.js"></script>

<!-- chartjs -->
<script type="text/javascript" src="js/plugins/chart.min.js"></script>
<script type="text/javascript" src="js/plugins/chart-script.js"></script>

<!-- sparkline -->
<script type="text/javascript" src="js/plugins/jquery.sparkline.min.js"></script>
<script type="text/javascript" src="js/plugins/sparkline-script.js"></script>

<!-- google map api -->
<!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAAZnaZBXLqNBRXjd-82km_NO7GUItyKek"></script>-->

<!--jvectormap-->
<script type="text/javascript" src="js/plugins/jquery-jvectormap-1.2.2.min.js"></script>
<script type="text/javascript" src="js/plugins/jquery-jvectormap-world-mill-en.js"></script>
<script type="text/javascript" src="js/plugins/vectormap-script.js"></script>

<!--google map-->
<!--<script type="text/javascript" src="js/plugins/google-map-script.js"></script>-->


<!--plugins.js - Some Specific JS codes for Plugin Settings-->
<script type="text/javascript" src="js/plugins/plugins.min.js"></script>
<!--custom-script.js - Add your own theme custom JS-->
<script type="text/javascript" src="js/plugins/custom-script.js"></script>
<!-- Toast Notification -->
<script type="text/javascript">
	// Toast Notification
	$(window).load(function() {
		setTimeout(function() {
			Materialize.toast('<span>Hiya! I am a toast.</span>', 1500);
		}, 1500);
		setTimeout(function() {
			Materialize.toast('<span>You can swipe me too!</span>', 3000);
		}, 5000);
		setTimeout(function() {
			Materialize.toast('<span>You have new order.</span><a class="btn-flat yellow-text" href="#">Read<a>', 3000);
		}, 15000);
	});
</script>
</body>

</html>
