google.maps.__gjsload__('map', function(_){var Ax=function(a,b,c,d,e,f,g){var h=new _.gu;_.hu(h,a,b);null!=c&&_.ku(h,c,0,d);g&&g.forEach(function(a){return _.mu(h,a,c)});e&&_.v(e,function(a){_.pj(_.ht(_.au(h.b)),a)});f&&_.nu(h,f);return h.b},Bx=function(a,b,c,d,e,f,g,h,l,n,q,r,u,B){_.Pg.call(this);this.B=a;this.l=b;this.projection=c;this.maxZoom=d;this.tileSize=new _.L(256,256);this.name=e;this.alt=f;this.G=g;this.heading=B;this.F=_.y(B);this.Hc=h;this.__gmsd=l;this.pa=n;this.f=null;this.D=q;this.m=r;this.C=u;this.qd=!0;this.j=_.Ld({})},Cx=
function(a,b,c,d,e,f,g,h,l){var n=[];if(e){var q=new _.Wk;q.data[0]=e.type;if(e.params)for(var r in e.params){var u=_.Xk(q);_.Fk(u,r);var B=e.params[r];B&&(u.data[1]=B)}n.push(q)}e=new _.Wk;e.data[0]=37;_.Fk(_.Xk(e),"smartmaps");n.push(e);return{ua:Ax(a,b,c,d,n,f,l),wb:g,scale:h}},Dx=function(a){this.data=a||[]},Ex=function(a,b,c){_.jn.call(this);this.D=null!=c?(0,_.p)(a,c):a;this.m=b;this.l=(0,_.p)(this.G,this);this.f=this.b=null;this.j=[]},Fx=function(a,b,c,d,e){Bx.call(this,a.B,a.l,a.projection,
a.maxZoom,a.name,a.alt,a.G,a.Hc,a.__gmsd,a.pa,a.D,a.m,a.C,a.heading);this.l&&this.j.set(Cx(this.m,this.C,this.pa,this.D,this.__gmsd,b,c,d,e))},Gx=function(a){var b=Math.round(1E7*a);return 0>a?b+4294967296:b},Hx=function(a,b){a=_.fe(new _.oj(a.b.data[7]),0).slice();return _.Gl(a,function(a){return a+"deg="+b+"&"})},Ix=function(a,b){return _.Ak(a.get("projection"),b,a.get("zoom"),a.get("offset"),a.get("center"))},Jx=function(a,b){for(var c=a.length,d=_.Ea(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,
d[e],e,a))return!1;return!0},Kx=function(a,b,c,d){d=void 0===d?{}:d;this.W=a;this.f=b;this.b=c.slice(0);this.j=d.fb||_.Ga},Lx=function(a){var b=this;this.tileSize=a[0].tileSize;this.Oa=a[0].Oa;this.Lb=a[0].Lb;this.b=a;this.dc=a[0].dc;Jx(a,function(a){var c=a.tileSize,e=b.tileSize;return c.Wb==e.Wb&&c.Xb==e.Xb&&a.Oa==b.Oa})},Mx=function(a){switch(a.pa){case "roadmap":return"Otm";case "satellite":return"Otk";case "hybrid":return"Oth";case "terrain":return"Otr"}return a instanceof _.Qg?"Ots":"Oto"},
Nx=function(a,b){if(!a)return null;var c=!0,d=a.tileSize,e=a.Oa;_.v(b,function(a){if(!a)return null;c=c&&d.Wb==a.tileSize.width&&d.Xb==a.tileSize.height&&e==a.qd});if(!c)return null;if(0==b.length)return a;var f=[];_.v(b,function(a){if(!a)return null;f.push(a instanceof _.Pg?a.b():new _.Eu(a))});return new Lx([a].concat(f))},Qx=function(a,b){var c=null,d=null,e=null;return function(f,g){if(d==f&&e==g)return c;d=f;e=g;_.v(f,function(b){b&&a(Mx(b))});c=null;g instanceof _.Pg?c=g.b():g&&(c=new _.Eu(g));
(f=Nx(c,f))?(c=f,b&&Ox(b)):b&&Px(b);return c}},Tx=function(a,b){this.j=a;this.f=b;this.P=[_.z.bind(b,"insert_at",this,this.l),_.z.bind(b,"remove_at",this,this.m),_.z.bind(b,"set_at",this,this.B)];this.b=[];var c=this;this.f.forEach(function(a){a=Rx(c,a);c.b.push(a)});Sx(this)},Sx=function(a){_.v(a.b,function(a,c){a.set("zIndex",c)})},Rx=function(a,b){var c=new _.Hu(a.j,null);c.bindTo("size",a);c.bindTo("zoom",a);c.bindTo("offset",a);c.bindTo("projectionBounds",a);_.Ku(c,b);c.listener=b&&_.z.forward(c,
"tilesloaded",b);return c},Ux=function(a){a.release();a.listener&&(_.z.removeListener(a.listener),delete a.listener)},Vx=function(a,b){this.j=a;this.f=b;_.z.bind(this,"tilesloaded",this,this.l);this.b=null},Ox=function(a){a.b&&(a.b.ga(),a.b.unbindAll(),a.b=null)},Px=function(a){a.b||(a.b=new Tx(a.j,a.f),a.b.bindTo("size",a),a.b.bindTo("zoom",a),a.b.bindTo("offset",a),a.b.bindTo("projectionBounds",a))},Wx=function(a,b){for(var c=0,d=a.f,e=a.b,f=0,g;g=b[f++];)if(a.intersects(g)){var h=g.f,l=g.b;if(_.Bj(g,
a))return 1;g=e.contains(l.b)&&l.contains(e.b)&&!_.ed(e,l)?_.fd(l.b,e.f)+_.fd(e.b,l.f):_.fd(e.contains(l.b)?l.b:e.b,e.contains(l.f)?l.f:e.f);c+=g*(Math.min(d.b,h.b)-Math.max(d.f,h.f))}return c/=_.jd(d)*_.dd(e)},Yx=function(a,b,c,d,e,f){this.W=a.W;this.b=a;this.j=_.Gl(b||[],function(a){return a.replace(/&$/,"")});this.B=c;this.l=d;this.f=e;this.m=f||null;Xx(this)},Xx=function(a){for(var b=2==a.f||4==a.f?a.f:1,b=Math.min(1<<a.W.da,b),c=a.B&&4!=b,d=a.W.da,e=b;1<e;e/=2)d--;if(e=a.l({ca:a.W.ca,ba:a.W.ba,
da:a.W.da}))d=_.zk(_.zk(_.zk(new _.tk(_.pu(a.j,e)),"x",e.ca),"y",e.ba),"z",d),1!=b&&_.zk(d,"w",256/b),c&&(b*=2),1!=b&&_.zk(d,"scale",b),a.b.setUrl(d.toString(),a.m)},Zx=function(a,b){var c=a.x,d=a.y;switch(b){case 90:a.x=d;a.y=256-c;break;case 180:a.x=256-c;a.y=256-d;break;case 270:a.x=256-d,a.y=c}},dy=function(a){if(!a)return"";var b=[];a=_.Jl(a);for(var c=a.next();!c.done;c=a.next()){var d=c.value,e=d.elementType,f=d.stylers,c=[],d=(d=d.featureType)&&$x[d.toLowerCase()];(d=null!=d?d:null)&&c.push("s.t:"+
d);(e=e&&ay[e.toLowerCase()]||null)&&c.push("s.e:"+e);if(f)for(f=_.Jl(f),d=f.next();!d.done;d=f.next()){a:{e=void 0;d=d.value;for(e in d){var g=d[e],h=e&&by[e.toLowerCase()]||null;if(h&&(_.y(g)||_.mb(g)||_.nb(g))&&g){"color"==e&&cy.test(g)&&(g="#ff"+g.substr(1));e="p."+h+":"+g;break a}}e=void 0}e&&c.push(e)}(c=c.join("|"))&&b.push(c)}b=b.join(",");return 1E3>=b.length?b:""},ey=function(a,b,c,d,e){this.f=a;a=_.pq(this,"apistyle");var f=_.pq(this,"authUser"),g=_.pq(this,"baseMapType"),h=_.pq(this,"scale"),
l=_.pq(this,"tilt");this.b=null;var n=(0,_.p)(this.fk,this);b=new _.xo([a,f,b,g,h,l],n);_.nq(this,"tileMapType",b);this.l=_.Ld([]);a=(0,_.p)(this.gn,this,c);_.z.bind(c,"insert_at",this,a);_.z.bind(c,"remove_at",this,a);_.z.bind(c,"set_at",this,a);a();this.B=new _.xo([this.l,b],Qx(e,d))},hy=function(a,b,c,d,e,f,g,h,l,n){this.H=a;this.l=g;this.X=e;this.f=f;this.D=h;this.F=c;this.b=b;this.B=d;this.m=this.j=0;_.z.T(this.b,"contextmenu",this,this.Sf);a=new _.Qv(this.b);_.z.bind(a,"mousewheel",this,this.ke);
a.bindTo("enabled",this,"scrollwheel");n={Al:_.Hl(_.cn,this.H),Ja:this.f.get("eventCapturer"),kc:this.f.get("panBlock"),mode:n};l=new _.Bu(this.b,!0,n,l);fy(this,l);gy(this,l);l.bindTo("draggable",this);l.bindTo("draggingCursor",this);l.bindTo("draggableCursor",this);_.z.forward(this.l,"forceredraw",this.H);_.z.forward(this.l,"tilesloaded",this.H)},iy=function(a){var b=a.get("zoom");var c=b;var d=a.get("zoomRange");d&&(c=_.iv(d,c));b!=c&&a.set("zoom",c)},fy=function(a,b){_.z.bind(b,"click",a,a.Hi);
_.z.bind(b,"dblclick",a,a.Xl);_.z.bind(b,"mousedown",a,a.Ii);_.v(["mouseover","mousemove","mouseout","mousedown","mouseup"],function(c){_.z.addListener(b,c,(0,_.p)(a.be,a,c))});var c=new _.Lv(b);c.bindTo("disabled",a,"disablePanMomentum");var d=a.f.get("mouseEventTarget");_.v(["movestart","move","moveend"],function(b){_.z.addListener(d,b,function(c){jy(a,b,c)});_.z.addListener(c,b,function(c){jy(a,b,c)})});_.z.forward(b,"mousedown",a.l);_.z.addListener(d,"mousewheel",(0,_.p)(a.ke,a))},jy=function(a,
b,c){c&&(c.latLng=a.X.fromContainerPixelToLatLng(c.fa));_.z.trigger(a.f,b,c);c&&_.Vp(c)||_.z.trigger(a.l,b,c)},gy=function(a,b){_.z.addListener(b,"movestart",(0,_.p)(function(){_.z.trigger(this.H,"dragstart")},a));_.z.addListener(b,"move",(0,_.p)(function(){_.z.trigger(this.H,"drag")},a));_.z.addListener(b,"moveend",(0,_.p)(function(){_.z.trigger(this.H,"dragend")},a))},ky=function(a,b){this.j=a;this.l=b},ly=function(){var a=!1;return function(b,c){if(b&&c){if(.999999>Wx(b,c))return a=!1;b=_.Qk(b,
(_.Tw-1)/2);return.999999<Wx(b,c)?a=!0:a}}},my=function(){return function(a,b){if(a&&b)return.9<=Wx(a,b)}},ny=_.oa("b"),oy=function(a){var b=window.document.createElement("div");_.em(b);_.im(b,0);a.appendChild(b);this.set("div",b)},qy=function(a){var b={};b.firstmap=py;b.hdpi=1<_.Pk();b.mob=!_.X.C;b.staticmap=a;return b},ry=function(a,b,c,d){function e(){if(!g.b&&!g.f){var n=c.get(),q=b.get("center"),r=b.get("zoom");null!=r&&q&&n&&n.width&&n.height&&(c.removeListener(e),h.remove(),l.remove(),d.size=
n.width+"x"+n.height,d.hadviewport=f,g.f=q,g.m=r,g.b=_.Bf("map2",{startTime:f?a:void 0,Bm:d}))}}this.H=b;this.j={};this.m=this.f=this.b=null;this.l=!1;var f=!0,g=this,h=b.addListener("center_changed",e),l=b.addListener("zoom_changed",e);c.addListener(e);e();f=!1},sy=function(a,b,c){!a.b||a.j[b]||a.l||(a.f.b(a.H.get("center"))&&a.m==a.H.get("zoom")?(a.j[b]=!0,c.call(a)):a.l=!0)},ty=function(a,b){sy(a,"staticmap",function(){var a={staticmap:b};sy(this,"firstpixel",function(){a.firstpixel=b});sy(this,
"allpixels",function(){a.allpixels=b});_.zf(this.b,a)})},uy=function(a,b){this.tileSize=a.tileSize;this.Oa=!0;this.f=a;this.b=b;this.Lb=_.Vi;this.dc=!1},vy=function(a,b,c,d,e,f,g,h){this.tileSize={Wb:b.width,Xb:b.height};this.l=c;this.b=a||[];this.B=b;this.j=d;this.C=e;this.f=f;this.m=g;this.Oa=!0;this.dc=!1;this.Lb=h},wy=function(a,b){this.j=b||new _.Of;this.b=new _.od(a%360,45);this.l=new _.J(0,0);this.f=!0},xy=function(){var a=new ny(my()),b={};b.obliques=new ny(ly());b.report_map_issue=a;return b},
yy=function(a){var b=new Ex(_.Hl(_.z.trigger,a,"idle"),300);b.B();_.z.addListener(a,"bounds_changed",(0,_.p)(b.B,b))},zy=function(a){if(a&&_.$l(a.getDiv())&&(_.Vl()||_.Ul())){_.cn(a,"Tdev");var b=window.document.querySelector('meta[name="viewport"]');(b=b&&b.content)&&b.match(/width=device-width/)&&_.cn(a,"Mfp")}},Ay=function(a,b){function c(){var c=b.get("baseMapType");if(c)switch(c.pa){case "roadmap":_.cn(a,"Tm");break;case "satellite":c.F&&_.cn(a,"Ta");_.cn(a,"Tk");break;case "hybrid":c.F&&_.cn(a,
"Ta");_.cn(a,"Th");break;case "terrain":_.cn(a,"Tr");break;default:_.cn(a,"To")}}c();_.z.addListener(b,"basemaptype_changed",c)},Cy=function(a,b,c){_.cb(_.hh,function(d,e){b.set(e,By(a,e,{Bk:c}))})},Dy=function(a,b){this.b=a;this.f=b},Ey=function(a){var b=this;this.b=a;a.addListener(function(){return b.notify("style")})},Fy=function(a,b){function c(c){var d=b.getAt(c);if(d instanceof _.Qg){c=d.get("styles");var f=dy(c);d.b=function(){var b=By(a,d.f);return(new Fx(b,f,null,null,null)).b()}}}_.z.addListener(b,
"insert_at",c);_.z.addListener(b,"set_at",c);b.forEach(function(a,b){return c(b)})},Gy=function(a,b,c){if((_.Vl()||_.Ul())&&!_.sm()){_.cn(b,"Mmni");var d=window.setInterval(function(){var e=a.b.getBoundingClientRect();if(e=!(0>=e.top-5&&0>=e.left-5&&e.height+5>=window.document.body.scrollHeight&&e.width+5>=window.document.body.scrollWidth))e=a.b.getBoundingClientRect(),e=0>=e.top-5&&0>=e.left-5&&e.bottom+5>=window.innerHeight&&e.right+5>=window.innerWidth&&"greedy"==c.get();e&&(_.cn(b,"Mmus"),window.clearInterval(d))},
1E3)}},Hy=_.oa("b"),Jy=function(a){var b=(b=window.navigator.connection||window.navigator.mozConnection||window.navigator.webkitConnection||null)&&b.type;_.cn(a,"Nt",b&&Iy[b]||"-na")},Ly=function(){Ky(this)},Ky=function(a){var b=new _.hv(a.get("minZoom")||0,a.get("maxZoom")||30),c=a.get("mapTypeMinZoom"),d=a.get("mapTypeMaxZoom"),e=a.get("trackerMaxZoom");_.y(c)&&(b.min=Math.max(b.min,c));_.y(e)?b.max=Math.min(b.max,e):_.y(d)&&(b.max=Math.min(b.max,d));a.set("zoomRange",b)},My=function(){this.B=new _.Wf;
this.l={};this.j={}},Ny=_.na(),Oy=_.na(),Py=function(a,b){var c=a.__gm,d=a.mapTypes,e=a.__gm;b=new Vx(b,a.overlayMapTypes);b.bindTo("size",e);b.bindTo("zoom",e);b.bindTo("offset",e);b.bindTo("projectionBounds",e);_.z.forward(a,"tilesloaded",b);d=new ey(d,c.b,a.overlayMapTypes,b,_.Hl(_.cn,a));d.bindTo("heading",a);d.bindTo("mapTypeId",a);_.og[23]&&d.bindTo("scale",a);d.bindTo("apistyle",c);d.bindTo("authUser",c);d.bindTo("tilt",c);return d},Qy=function(a,b){_.z.Ka(window,"resize",a);_.z.forward(a,
"resize",b);_.z.bind(b,"resize",this,this.b);this.f=b;this.b()},Ry=function(a,b,c,d,e,f,g,h){var l=c.__gm,n=new hy(c,a,b,!!c.U,e,l,d,g,(0,_.p)(f.b,f),h);n.bindTo("draggingCursor",c);n.bindTo("draggableMap",c,"draggable");_.z.addListener(c,"zoom_changed",function(){n.get("zoom")!=c.get("zoom")&&n.set("zoom",c.get("zoom"))});n.set("zoom",c.get("zoom"));n.bindTo("disablePanMomentum",c);n.bindTo("projectionTopLeft",e);n.bindTo("draggableCursor",l,"cursor");d.bindTo("zoom",n);e.bindTo("zoom",n);return n},
Sy=function(a,b,c,d){return d?new ky(a,function(){return b}):_.og[23]?new ky(a,function(a){var d=c.get("scale");return 2==d||4==d?b:a}):a},Ty=function(a,b){var c=a.__gm;b=new oy(b);b.bindTo("center",a);b.bindTo("projectionBounds",c);b.bindTo("offset",c);return b},Uy=function(){var a,b=new _.E;b.bounds_changed=function(){var c=b.get("bounds");c?a&&_.yj(a,c)||(a=_.Bd(c.I-512,c.J-512,c.K+512,c.L+512),b.set("boundsQ",a)):b.set("boundsQ",c)};return b},Vy=function(a,b,c,d){var e=new ry(a,b,c,qy(!!d));py=
!1;d&&_.xj(d,function g(a){a&&(d.removeListener(g),ty(e,a))});_.z.addListenerOnce(b,"tilesloaded",(0,_.p)(e.C,e));return e},Wy=_.oa("b"),Xy=function(a,b,c){var d=_.mj(),e=_.xf(_.R);this.H=b;this.b=c;this.j=new _.Of;this.f=_.vf(e);this.l=_.wf(e);this.B=_.O(d,14);this.m=_.O(d,15);this.C=new _.du(a,d,e)},Yy=function(a,b,c,d){d=void 0===d?{va:null}:d;var e=_.y(d.heading),f=("hybrid"==b&&!e||"terrain"==b||"roadmap"==b)&&0!=d.Yj,g=d.va;return"satellite"==b?(a=e?Hx(a.C,d.heading||0):_.fe(new _.oj(a.C.b.data[1]),
0).slice(),e=new _.Xf(e?45:0,d.heading||0),new vy(a,new _.L(256,256),"\u0422\u0443\u0442 \u043d\u0435\u043c\u0430\u0454 \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f.",window.document,f&&1<_.Pk(),_.yu(d.heading),g&&g.scale||null,e)):new _.xu(_.eu(a.C),new _.L(256,256),"\u0422\u0443\u0442 \u043d\u0435\u043c\u0430\u0454 \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f.",window.document,f&&1<_.Pk(),_.yu(d.heading),c,g,d.heading)},Zy=function(a){function b(a,b){if(!b||!b.ua)return b;
var c=[];_.ij(c,b.ua.data);c=new _.ut(c);_.ht(_.au(c)).data[0]=a;return{scale:b.scale,wb:b.wb,ua:c}}return function(c){var d=Yy(a,"roadmap",a.b,{Yj:!1,va:b(3,c.va().get())}),e=Yy(a,"roadmap",a.b,{va:b(18,c.va().get())}),d=new Lx([d,e]);c=Yy(a,"roadmap",a.b,{va:c.va().get()});return new uy(d,c)}},$y=function(a){return function(b){var c=b.va().get(),d=Yy(a,"satellite",null,{heading:b.heading,va:c});b=Yy(a,"hybrid",a.b,{heading:b.heading,va:c});return new Lx([d,b])}},az=function(a,b){return new Bx($y(a),
a.b,_.Fa(b)?new wy(b):a.j,_.Fa(b)?21:22,"\u041a\u043e\u043c\u0431\u0456\u043d\u043e\u0432\u0430\u043d\u0430","\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u0438 \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f \u0437 \u043d\u0430\u0437\u0432\u0430\u043c\u0438 \u0432\u0443\u043b\u0438\u0446\u044c",_.Aw.hybrid,"m@"+a.B,{type:68,params:{set:"RoadmapSatellite"}},"hybrid",a.m,a.f,a.l,b)},bz=function(a){return function(b){return Yy(a,"satellite",null,{heading:b.heading,va:b.va().get()})}},cz=
function(a,b){var c=_.Fa(b);return new Bx(bz(a),null,_.Fa(b)?new wy(b):a.j,c?21:22,"\u0421\u0443\u043f\u0443\u0442\u043d\u0438\u043a","\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u0438 \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f \u0456\u0437 \u0441\u0443\u043f\u0443\u0442\u043d\u0438\u043a\u0430",c?"a":_.Aw.satellite,null,null,"satellite",a.m,a.f,a.l,b)},dz=function(a,b){return function(c){return Yy(a,b,a.b,{va:c.va().get()})}},By=function(a,b,c){c=void 0===c?{}:c;var d=[0,90,180,
270];if("hybrid"==b)for(b=az(a),b.f={},d=_.Jl(d),c=d.next();!c.done;c=d.next())c=c.value,b.f[c]=az(a,c);else if("satellite"==b)for(b=cz(a),b.f={},d=_.Jl(d),c=d.next();!c.done;c=d.next())c=c.value,b.f[c]=cz(a,c);else b="roadmap"==b&&1<_.Pk()&&c.Bk?new Bx(Zy(a),a.b,a.j,22,"\u041a\u0430\u0440\u0442\u0430","\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u0438 \u043a\u0430\u0440\u0442\u0443 \u0432\u0443\u043b\u0438\u0446\u044c",_.Aw.roadmap,"m@"+a.B,{type:68,params:{set:"Roadmap"}},"roadmap",a.m,a.f,a.l,void 0):
"terrain"==b?new Bx(dz(a,"terrain"),a.b,a.j,21,"\u041b\u0430\u043d\u0434\u0448\u0430\u0444\u0442","\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u0438 \u043a\u0430\u0440\u0442\u0443 \u0432\u0443\u043b\u0438\u0446\u044c \u0456\u0437 \u043b\u0430\u043d\u0434\u0448\u0430\u0444\u0442\u043e\u043c",_.Aw.terrain,"r@"+a.B,{type:68,params:{set:"Terrain"}},"terrain",a.m,a.f,a.l,void 0):new Bx(dz(a,"roadmap"),a.b,a.j,22,"\u041a\u0430\u0440\u0442\u0430","\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u0438 \u043a\u0430\u0440\u0442\u0443 \u0432\u0443\u043b\u0438\u0446\u044c",
_.Aw.roadmap,"m@"+a.B,{type:68},"roadmap",a.m,a.f,a.l,void 0);return b},ez=_.na();_.Kl(Bx,_.Pg);Bx.prototype.b=function(){return this.B(this)};Bx.prototype.va=_.sa(12);Bx.prototype.va=_.lj(12,_.pa("j"));_.Wf.prototype.b=_.lj(7,function(a){_.Gd(this.P,function(b){b(a)})});_.t(Dx,_.N);Dx.prototype.getTile=function(){return new _.it(this.data[1])};_.t(Ex,_.jn);Ex.prototype.B=function(a){this.j=arguments;this.b?this.f=_.Ra()+this.m:this.b=_.Pn(this.l,this.m)};
Ex.prototype.stop=function(){this.b&&(_.Ub.clearTimeout(this.b),this.b=null);this.f=null;this.j=[]};Ex.prototype.Ca=function(){this.stop();Ex.ib.Ca.call(this)};Ex.prototype.G=function(){this.f?(this.b=_.Pn(this.l,this.f-_.Ra()),this.f=null):(this.b=null,this.D.apply(null,this.j))};_.Kl(Fx,Bx);Kx.prototype.ta=_.pa("f");Kx.prototype.Bb=function(){return Jx(this.b,function(a){return a.Bb()})};Kx.prototype.release=function(){for(var a=_.Jl(this.b),b=a.next();!b.done;b=a.next())b.value.release();this.j()};
Kx.prototype.freeze=function(){for(var a=_.Jl(this.b),b=a.next();!b.done;b=a.next())b.value.freeze()};Lx.prototype.Fa=function(a,b){function c(){b.eb&&f.Bb()&&b.eb()}b=void 0===b?{}:b;var d=_.rk(window.document,"DIV"),e=_.Gl(this.b,function(b,e){b=b.Fa(a,{eb:c});var f=b.ta();f.style.position="absolute";f.style.zIndex=e;d.appendChild(f);return b}),f=new Kx(a,d,e,{fb:b.fb});return f};
var by={hue:"h",saturation:"s",lightness:"l",gamma:"g",invert_lightness:"il",visibility:"v",color:"c",weight:"w"},cy=/^#[0-9a-fA-F]{6}$/,$x={all:0,administrative:1,"administrative.country":17,"administrative.province":18,"administrative.locality":19,"administrative.neighborhood":20,"administrative.land_parcel":21,poi:2,"poi.business":33,"poi.government":34,"poi.school":35,"poi.medical":36,"poi.attraction":37,"poi.place_of_worship":38,"poi.sports_complex":39,"poi.park":40,road:3,"road.highway":49,
"road.highway.controlled_access":785,"road.arterial":50,"road.local":51,transit:4,"transit.line":65,"transit.station":66,"transit.station.rail":1057,"transit.station.bus":1058,"transit.station.airport":1059,"transit.station.ferry":1060,landscape:5,"landscape.man_made":81,"landscape.natural":82,"landscape.natural.landcover":1313,"landscape.natural.terrain":1314,water:6},ay={all:"",geometry:"g","geometry.fill":"g.f","geometry.stroke":"g.s",labels:"l","labels.icon":"l.i","labels.text":"l.t","labels.text.fill":"l.t.f",
"labels.text.stroke":"l.t.s"};_.t(Tx,_.E);Tx.prototype.ga=function(){_.v(this.b,function(a){Ux(a)},this);this.b.length=0;_.v(this.P,function(a){a.remove()})};Tx.prototype.l=function(a){var b=this.b,c=Rx(this,this.f.getAt(a));b.splice(a,0,c);Sx(this)};Tx.prototype.m=function(a){var b=this.b;Ux(b[a]);b.splice(a,1);Sx(this)};Tx.prototype.B=function(a){Ux(this.b[a]);var b=Rx(this,this.f.getAt(a));b.set("zIndex",a);this.b[a]=b};
var fz=[{fe:108.25,ee:109.625,je:49,ie:51.5},{fe:109.625,ee:109.75,je:49,ie:50.875},{fe:109.75,ee:110.5,je:49,ie:50.625},{fe:110.5,ee:110.625,je:49,ie:49.75}];_.t(Vx,_.E);Vx.prototype.l=function(){this.b||this.f.forEach(function(a){a&&_.z.trigger(a,"tilesloaded")})};var py=!0;Yx.prototype.ta=function(){return this.b.ta()};Yx.prototype.Bb=function(){return this.b.Bb()};Yx.prototype.release=function(){this.b.release()};Yx.prototype.freeze=function(){this.b.freeze()};
var Iy={bluetooth:"-b",cellular:"-c",ethernet:"-e",none:"-n",wifi:"-wf",wimax:"-wm",other:"-o"};_.t(ey,_.E);_.k=ey.prototype;_.k.mapTypeId_changed=function(){var a=this.get("mapTypeId");this.rd(a)};_.k.heading_changed=function(){var a=this.get("heading");if(_.Fa(a)){var b=_.gb(90*Math.round(a/90),0,360);a!=b?this.set("heading",b):(a=this.get("mapTypeId"),this.rd(a))}};_.k.tilt_changed=function(){var a=this.get("mapTypeId");this.rd(a)};_.k.gn=function(a){this.l.set(a.getArray().slice())};
_.k.setMapTypeId=function(a){this.rd(a);this.set("mapTypeId",a)};
_.k.rd=function(a){var b=this.get("heading")||0,c=this.f.get(a),d=this.get("tilt");if(d&&c&&c instanceof Bx&&c.f&&c.f[b])c=c.f[b];else if(0==d&&0!=b){this.set("heading",0);return}c&&c==this.m||(this.j&&(_.z.removeListener(this.j),this.j=null),b=(0,_.p)(this.rd,this,a),a&&(this.j=_.z.addListener(this.f,a.toLowerCase()+"_changed",b)),c&&c instanceof _.Qg?(a=c.f,this.set("styles",c.get("styles")),this.set("baseMapType",this.f.get(a))):(this.set("styles",null),this.set("baseMapType",c)),this.set("maxZoom",
c&&c.maxZoom),this.set("minZoom",c&&c.minZoom),this.m=c)};
_.k.fk=function(a,b,c,d,e,f){if(void 0==f)return null;if(d instanceof Bx){a=new Fx(d,a,b,e,c);if(b=this.b instanceof Fx)if(b=this.b,b==a)b=!0;else if(b&&a){if(c=b.heading==a.heading&&b.projection==a.projection&&b.Hc==a.Hc){b=b.j.get();c=a.j.get();if(b==c)b=!0;else if(b&&c){if(d=b.scale==c.scale&&b.wb==c.wb)b.ua==c.ua?b=!0:b.ua&&c.ua?(c=c.ua,b=_.Td(b.ua.data,c?c.data:null)):b=!1,d=b;b=d}else b=!1;c=b}b=c}else b=!1;b||(this.b=a)}else this.b=d;return this.b};_.t(hy,_.E);_.k=hy.prototype;
_.k.zoom_changed=function(){iy(this)};_.k.zoomRange_changed=function(){iy(this)};_.k.Sf=function(a){var b=_.Hk();300>=b-this.m?(this.m=0,this.get("disableDoubleClickZoom")||this.ke(_.bn(a,this.b),-1)):(this.m=b,this.be("rightclick",a));_.ub(a);_.vb(a);this.C=!0};_.k.Xl=function(a){1<a.button||_.Cj(a)||(this.be("dblclick",a),_.Cj(a)||(this.j=0,this.get("disableDoubleClickZoom")||(a=_.bn(a,this.b),this.ke(a,1))))};
_.k.Hi=function(a){if(!_.Cj(a)&&!this.C){var b=_.Hk();300>=b-this.j?this.j=0:(this.j=b,this.be("click",a));_.en("Mm","-i",this,this.B)}};
_.k.be=function(a,b){var c=_.bn(b,this.F),d=_.bn(b,this.b),e=this.X.fromDivPixelToLatLng(c,!0);if(e){c=new _.F(e.lat(),e.lng());e=this.H.get("projection").fromLatLngToPoint(e);b=new _.yl(c,b,d,e);var d=this.f.f,c=_.Wl(),e=d.l,f=b.Ba&&_.Cj(b.Ba);if(d.b){var g=d.b;var h=d.j}else if("mouseout"==a||f)h=g=null;else{for(var l=0;(g=e[l++])&&!(h=g.b(b,!1)););if(!h&&c)for(l=0;(g=e[l++])&&!(h=g.b(b,!0)););}if(g!=d.f||h!=d.m)d.f&&d.f.handleEvent("mouseout",b,d.m),d.f=g,d.m=h,g&&g.handleEvent("mouseover",b,h);
g?"mouseover"==a||"mouseout"==a?h=!1:(g.handleEvent(a,b,h),h=!0):h=!!f;h||(this.set("draggableCursor",this.H.get("draggableCursor")),this.D.get("title")&&this.D.set("title",null),delete b.Ba,_.z.trigger(this.H,a,b))}};_.k.Ii=function(a){this.C=!1;5!=_.X.type||2!=_.X.b||2!=a.button||a.ctrlKey||this.Sf(a)};
_.k.ke=function(a,b){b=Math.pow(2,b);var c=new _.Sp(0,0,b);_.Tp(c,new _.J(-a.x,-a.y));a=new _.Rp(b,new _.J(c.x,c.y),a);jy(this,"movestart",null);jy(this,"move",a);jy(this,"moveend",a);_.en("Mm","-i",this,this.B)};ky.prototype.m=function(a){return this.l(this.j.m(a))};ky.prototype.f=function(a){return this.l(this.j.f(a))};ky.prototype.b=function(){return this.j.b()};_.t(ny,_.E);
ny.prototype.changed=function(a){if("available"!=a){a=this.get("viewport");var b=this.get("featureRects");a=this.b(a,b);null!=a&&a!=this.get("available")&&this.set("available",a)}};_.t(oy,_.E);oy.prototype.offset_changed=function(){this.set("newCenter",this.get("center"));var a=this.get("projectionBounds"),b=this.get("offset");if(a&&b){var c=this.get("div");_.am(c,new _.J(a.I-b.width,a.J-b.height));_.fm(c)}};ry.prototype.D=function(){sy(this,"visreq",function(){_.Af(this.b,"visreq")})};
ry.prototype.F=function(){sy(this,"visres",function(){_.Af(this.b,"visres")})};ry.prototype.B=function(){sy(this,"firsttile",function(){var a={firsttile:void 0};sy(this,"firstpixel",function(){a.firstpixel=void 0});_.zf(this.b,a)})};ry.prototype.C=function(){sy(this,"tilesloaded",function(){var a={tilesloaded:void 0};sy(this,"allpixels",function(){a.allpixels=void 0});_.zf(this.b,a)})};
uy.prototype.Fa=function(a,b){a:{var c=a.da;if(!(7>c)){var d=1<<c-7;c=a.ca/d;for(var d=a.ba/d,e=_.Jl(fz),f=e.next();!f.done;f=e.next())if(f=f.value,c>=f.fe&&c<=f.ee&&d>=f.je&&d<=f.ie){c=!0;break a}}c=!1}return c?this.b.Fa(a,b):this.f.Fa(a,b)};vy.prototype.Fa=function(a,b){a=new _.qu(a,this.B,this.j.createElement("div"),{Fg:this.l||void 0,fb:b&&b.fb});return new Yx(a,this.b,this.C,this.f,this.m,b&&b.eb)};
wy.prototype.fromLatLngToPoint=function(a,b){b=this.j.fromLatLngToPoint(a,b);Zx(b,this.b.heading());b.y=(b.y-128)/_.Rw+128;return b};wy.prototype.fromPointToLatLng=function(a,b){var c=this.l;c.x=a.x;c.y=(a.y-128)*_.Rw+128;Zx(c,360-this.b.heading());return this.j.fromPointToLatLng(c,b)};wy.prototype.getPov=_.pa("b");_.Kl(Dy,_.E);
Dy.prototype.getPrintableImageUri=function(a,b,c,d,e){d=void 0===d?0:d;e=void 0===e?1:e;var f=this.get("tileMapType");if(2048<a*e||2048<b*e||!(f instanceof Bx))return null;d=d||this.get("zoom");if(null==d)return null;c=c||this.get("center");if(!c)return null;var g=f.va().get();if(!g.ua)return null;var h=new _.gu(g.ua);_.iu(h,0);var l=this.f.f(d);l&&_.lu(h,l);if("hybrid"==f.pa){_.bu(h.b);for(f=_.he(h.b,1)-1;0<f;--f)_.pj(new _.Hs(_.qj(h.b,1,f)),new _.Hs(_.qj(h.b,1,f-1)));f=new _.Hs(_.qj(h.b,1,0));f.data[0]=
1;_.tj(f,1);_.tj(f,2)}if(2==e||4==e)(new _.Js(_.Q(h.b,4))).data[4]=e;e=d;d=new _.qt(_.Q(new _.nt(_.rj(h.b,0)),3));d.setZoom(e);e=new _.Oo(_.Q(d,2));f=Gx(c.lat());e.data[0]=f;c=Gx(c.lng());e.data[1]=c;d=new _.rt(_.Q(d,0));d.data[0]=a;d.data[1]=b;a=this.b;a+="pb="+(0,window.encodeURIComponent)(_.$t(h.b)).replace(/%20/g,"+");null!=g.wb&&(a+="&authuser="+g.wb);return a};_.Kl(Ey,_.E);Ey.prototype.changed=function(a){"tileMapType"!=a&&"style"!=a&&this.notify("style")};
Ey.prototype.getStyle=function(){var a=[],b=this.get("tileMapType");if(b instanceof Bx&&(b=b.__gmsd)){var c=new _.Wk;c.data[0]=b.type;if(b.params)for(var d in b.params){var e=_.Xk(c);_.Fk(e,d);var f=b.params[d];f&&(e.data[1]=f)}a.push(c)}d=new _.Wk;d.data[0]=37;_.Fk(_.Xk(d),"smartmaps");a.push(d);this.b.get().forEach(function(b){b.Vh&&a.push(b.Vh)});return a};_.t(Ly,_.E);Ly.prototype.changed=function(a){"zoomRange"!=a&&Ky(this)};
My.prototype.C=function(a){if(_.he(a,0)){this.l={};this.j={};for(var b=0;b<_.he(a,0);++b){var c=new Dx(_.qj(a,0,b)),d=c.getTile(),e=d.getZoom(),f=_.O(d,1),d=_.O(d,2),c=_.O(c,2),g=this.l;g[e]=g[e]||{};g[e][f]=g[e][f]||{};g[e][f][d]=c;this.j[e]=Math.max(this.j[e]||0,c)}this.B.b(null)}};My.prototype.m=function(a){var b=this.l,c=a.ca,d=a.ba;a=a.da;return b[a]&&b[a][c]&&b[a][c][d]||0};My.prototype.f=function(a){return this.j[a]||0};My.prototype.b=_.pa("B");_.t(Ny,_.E);
Ny.prototype.changed=function(a){if("apistyle"!=a&&"hasCustomStyles"!=a){var b=this.get("mapTypeStyles")||this.get("styles");this.set("hasCustomStyles",_.w(b));a=[];_.og[13]&&a.push({featureType:"poi.business",elementType:"labels",stylers:[{visibility:"off"}]});_.kb(a,b);b=dy(a);b!=this.b&&(this.b=b,this.notify("apistyle"));a.length&&!b&&_.ac(_.Hl(_.z.trigger,this,"styleerror"))}};Ny.prototype.getApistyle=_.pa("b");_.t(Oy,_.E);
Oy.prototype.changed=function(a){if("maxZoomRects"==a||"latLng"==a){a=this.get("latLng");var b=this.get("maxZoomRects");if(a&&b){for(var c=void 0,d=0,e;e=b[d++];)e.ya.contains(a)&&(c=Math.max(c||0,e.maxZoom));a=c;a!=this.get("maxZoom")&&this.set("maxZoom",a)}else this.set("maxZoom",void 0)}};_.t(Qy,_.E);Qy.prototype.b=function(){var a=new _.L(this.f.clientWidth,this.f.clientHeight);a.b(this.get("size"))||this.set("size",a)};_.t(Wy,_.E);
Wy.prototype.immutable_changed=function(){var a=this,b=a.get("immutable"),c=a.f;b!=c&&(_.cb(a.b,function(d){(c&&c[d])!==(b&&b[d])&&a.set(d,b&&b[d])}),a.f=b)};ez.prototype.f=function(a,b,c,d,e,f,g){var h=_.vf(_.xf(_.R)),l=a.__gm,n=a.getDiv();if(n){_.z.forward(n,"resize",c);_.z.addDomListenerOnce(c,"mousedown",function(){_.cn(a,"Mi")},!0);var q=new _.tw({tg:c,wg:n,ug:!0,Yg:_.vj(_.xf(_.R),15),backgroundColor:b.backgroundColor,Gf:!1,rl:1==_.X.type}),r=q.b,n=new Qy(c,q.j);_.im(q.j,0);_.z.forward(a,"resize",c);l.set("panes",q.D);l.set("innerContainer",q.m);var u=Vy(f,a,_.pq(n,"size"),d&&d.B),B=new Oy,x=xy(),A,D;(function(){var b=_.O(_.mj(),14),c=a.get("noPerTile")&&
_.og[15],d=new My;A=Sy(d,b,a,c);D=new _.cw(h,B,x,c?null:d,!!a.U,u)})();D.bindTo("tilt",a);D.bindTo("heading",a);D.bindTo("bounds",a);D.bindTo("zoom",a);D.bindTo("size",l);f=new Xy(new _.nj(_.Q(_.R,1)),a,A);Cy(f,a.mapTypes,b.enableSplitTiles);l.set("eventCapturer",q.B);l.set("panBlock",q.kc);var C=Py(a,q.D.mapPane);D.bindTo("baseMapType",C);var H=_.Ld(!1);f=_.Ao({draggable:_.pq(a,"draggable"),xg:_.pq(a,"gestureHandling"),Zc:H});var K=null;var I=new _.tv(r,q.f,C.B,u);var ba=new _.mq(["blockingLayerCount",
"staticMapLoading"],"waitWithTiles",function(a,b){return!!a||!!b});ba.bindTo("blockingLayerCount",l);I.bindTo("waitWithTiles",ba);I.set("panes",q.D);I.bindTo("styles",a);_.og[20]&&I.bindTo("animatedZoom",a);_.G("onion",function(b){b.f(a,A)});_.og[35]&&(_.uw(a),_.vw(a));var ya=new _.bw;ya.bindTo("tilt",a);ya.bindTo("zoom",a);ya.bindTo("mapTypeId",a);ya.bindTo("aerial",x.obliques,"available");l.bindTo("tilt",ya,"actualTilt");_.z.addListener(D,"attributiontext_changed",function(){a.set("mapDataProviders",
D.get("attributionText"))});ba=new Ny;ba.bindTo("styles",a);ba.bindTo("mapTypeStyles",C,"styles");l.bindTo("apistyle",ba);l.bindTo("hasCustomStyles",ba);_.z.forward(ba,"styleerror",a);ba=new Ey(l.b);ba.bindTo("tileMapType",C);l.bindTo("style",ba);if(I){var Ca=new _.Wv;l.set("projectionController",Ca);I.bindTo("size",n);I.bindTo("projection",Ca);I.bindTo("projectionBounds",Ca);Ca.bindTo("projectionTopLeft",I);Ca.bindTo("offset",I);Ca.bindTo("latLngCenter",a,"center");Ca.bindTo("size",n);Ca.bindTo("projection",
a);I.bindTo("fixedPoint",Ca);a.bindTo("bounds",Ca,"latLngBounds",!0)}l.set("mouseEventTarget",{});ba=new _.Vv(_.X.j,q.m);ba.bindTo("title",l);var xa;I&&(xa=Ry(q.m,r,a,I,Ca,g,ba,f));d&&(g=Ty(a,r),d.bindTo("div",g),d.bindTo("center",g,"newCenter"),xa&&d.bindTo("zoom",xa),d.bindTo("tilt",l),d.bindTo("size",l));xa?l.bindTo("zoom",xa):l.bindTo("zoom",a);l.bindTo("center",a);l.bindTo("size",n);l.bindTo("baseMapType",C);I&&(l.bindTo("offset",I),l.bindTo("layoutPixelBounds",I),l.bindTo("pixelBounds",I),l.bindTo("projectionTopLeft",
I),l.bindTo("projectionBounds",I,"viewProjectionBounds"),l.bindTo("projectionCenterQ",Ca));a.set("tosUrl",_.Fw);I&&(d=Uy(),d.bindTo("bounds",I,"pixelBounds"),l.bindTo("pixelBoundsQ",d,"boundsQ"));d=new Wy({projection:1});d.bindTo("immutable",l,"baseMapType");g=new _.lw({projection:new _.Of});g.bindTo("projection",d);a.bindTo("projection",g);I&&(_.z.forward(l,"panby",I),_.z.forward(l,"panbynow",I),_.z.forward(l,"panbyfraction",I));_.z.addListener(l,"panto",function(b){if(b instanceof _.F)if(!a.get("center"))a.set("center",
b);else{if(I){b=Ca.fromLatLngToDivPixel(b);var c=Ca.get("offset")||_.Sh;b.x+=Math.round(c.width)-c.width;b.y+=Math.round(c.height)-c.height;_.z.trigger(I,"panto",b.x,b.y)}}else throw Error("panTo: latLng must be of type LatLng");});I&&(_.z.forward(l,"pantobounds",I),_.z.addListener(l,"pantolatlngbounds",function(a){if(a instanceof _.kd)I&&_.z.trigger(I,"pantobounds",Ix(Ca,a));else throw Error("panToBounds: latLngBounds must be of type LatLngBounds");}));I&&xa&&_.z.addListener(xa,"zoom_changed",function(){xa.get("zoom")!=
a.get("zoom")&&(a.set("zoom",xa.get("zoom")),_.hn(a,"Mm"))});var Xa=new Ly;Xa.bindTo("mapTypeMaxZoom",C,"maxZoom");Xa.bindTo("mapTypeMinZoom",C,"minZoom");Xa.bindTo("maxZoom",a);Xa.bindTo("minZoom",a);Xa.bindTo("trackerMaxZoom",B,"maxZoom");I&&xa&&(xa.bindTo("zoomRange",Xa),I.bindTo("zoomRange",Xa),xa.bindTo("draggable",a),xa.bindTo("scrollwheel",a),xa.bindTo("disableDoubleClickZoom",a));var gc=new _.mw(_.$l(c));l.bindTo("fontLoaded",gc);d=l.j;d.bindTo("scrollwheel",a);d.bindTo("disableDoubleClickZoom",
a);d=function(){var b=a.get("streetView");b?(a.bindTo("svClient",b,"client"),b.__gm.bindTo("fontLoaded",gc)):(a.unbind("svClient"),a.set("svClient",null))};d();_.z.addListener(a,"streetview_changed",d);if(_.og[71]){var qc=null;_.Dl(a,"floor_changed",function(){var b=a.get("floor");if((qc&&qc.parameters.pid_lv)!=b){var c=qc,d=l.b.get();qc&&(c=null,d=d.Va(qc));b&&(c=new _.cu,c.la="indoor",c.parameters.pid_lv=b,d=_.Aj(d,c));qc=c;l.b.set(d)}})}if(!a.U){K=function(){K=null;_.G("controls",function(b){var d=
new b.Rf(q.j);l.set("layoutManager",d);I&&I.bindTo("layoutBounds",d,"bounds");b.Cl(d,a,C,q.j,D,x.report_map_issue,Xa,ya,c,H,Ca);b.Dl(a,q.m);b.Nh(c)})};if(I){var Ef=_.z.addListener(I,"tilesloading_changed",function(){I.get("tilesloading")&&(Ef.remove(),K())});_.z.addListenerOnce(I,"tilesloaded",function(){_.G("util",function(b){b.f.b();window.setTimeout((0,_.p)(b.b.f,b.b),5E3);b.l(a)})})}_.cn(a,"Mm");b.v2&&_.cn(a,"Mz");_.en("Mm","-p",a,!(!a||!a.U));Ay(a,C);_.hn(a,"Mm");_.um(function(){_.hn(a,"Mm")});
zy(a);c&&Gy(new Hy(c),a,f)}yy(a);var me=_.O(_.mj(),14);b=new Xy(new _.nj(_.Q(_.R,1)),a,new ky(A,function(a){return a||me}));Fy(b,a.overlayMapTypes);_.og[35]&&l.bindTo("card",a);a.U||Jy(a);e&&window.setTimeout(function(){_.z.trigger(a,"projection_changed");_.m(a.get("bounds"))&&_.z.trigger(a,"bounds_changed");_.z.trigger(a,"tilt_changed");_.m(a.get("heading"))&&_.z.trigger(a,"heading_changed")},0);_.og[15]&&(e=_.eu(_.fu()),e=new Dy(e[0],A),e.bindTo("tileMapType",C),e.bindTo("center",a),e.bindTo("zoom",
l),a.getPrintableImageUri=(0,_.p)(e.getPrintableImageUri,e),I&&(a.setFpsMeasurementCallback=(0,_.p)(I.setFpsMeasurementCallback,I),a.bindTo("tilesloading",I)),l.bindTo("authUser",a))}};
ez.prototype.fitBounds=function(a,b,c){function d(){var c=a.getHeading();180==c?(g*=-1,h*=-1):90==c?(c=g,g=h,h=c):270==c&&(c=-g,g=-h,h=c);var d=_.$f(a.getDiv());d.width-=e;d.width=Math.max(1,d.width);d.height-=f;d.height=Math.max(1,d.height);var c=a.getProjection(),l=b.getSouthWest(),n=b.getNorthEast(),q=l.lng(),D=n.lng();q>D&&(l=new _.F(l.lat(),q-360,!0));l=c.fromLatLngToPoint(l);q=c.fromLatLngToPoint(n);n=Math.max(l.x,q.x)-Math.min(l.x,q.x);l=Math.max(l.y,q.y)-Math.min(l.y,q.y);d=n>d.width||l>d.height?
0:Math.floor(Math.min(_.Ik(d.width+1E-12)-_.Ik(n+1E-12),_.Ik(d.height+1E-12)-_.Ik(l+1E-12)));n=_.pk(c,b,0);n=_.Ck(c,new _.J((n.I+n.K)/2,(n.J+n.L)/2),0);_.y(d)&&(n=new _.F(n.lat()+h/(_.ok(c,d)/360),n.lng()+g/(_.ok(c,d)/360)),a.setCenter(n),a.setZoom(d))}var e=80,f=80,g=0,h=0;if(_.Fa(c))e=f=2*c-.01;else if(c){var l=c.left||0,n=c.right||0,q=c.bottom||0;c=c.top||0;e=l+n-.01;f=c+q-.01;h=c-q;g=l-n}a.getProjection()?d():_.z.addListenerOnce(a,"projection_changed",d)};
ez.prototype.b=function(a,b,c,d,e){a=new _.qu(a,b,c,{});a.setUrl(d,e);return a};_.Wc("map",new ez);});
